import { getStore } from "@/lib/store";
import { chatComplete } from "@/lib/sarvamChat";

// sarvam-30b is a reasoning model (~45s for a batched reply); allow headroom.
export const maxDuration = 60;

type CallResult = {
  customerId: string;
  name: string;
  amount: number;
  transcript: { speaker: "AI" | "Customer"; text: string }[];
  outcome: string;
  promise: string | null;
};

// Simulated customer responses (the call is simulated; only the AI's opening
// line is generated by Sarvam). Varied by index so calls don't look identical.
const REPLIES = [
  { reply: "Haan ji, aaj shaam tak bhej deta hoon.", outcome: "Will pay today", promise: "today" },
  { reply: "Theek hai, do din mein clear kar dunga.", outcome: "Will pay in 2 days", promise: "in 2 days" },
  { reply: "Arre maine to kal hi UPI se bhej diya tha, check karo.", outcome: "Says already paid", promise: null },
  { reply: "Abhi thoda tight hoon, agle hafte pakka.", outcome: "Asked for a week", promise: "next week" },
  { reply: "Haan bilkul, kal subah aake de jaata hoon.", outcome: "Will pay tomorrow", promise: "tomorrow" },
];

// Pull a per-customer line out of the batched "Name: message" reply.
function lineFor(name: string, batched: string): string | null {
  const first = name.split(/\s+/)[0].toLowerCase();
  for (const raw of batched.split(/\r?\n/)) {
    const line = raw.trim().replace(/^[-*•\d.]+\s*/, "");
    const idx = line.indexOf(":");
    if (idx <= 0) continue;
    const who = line.slice(0, idx).toLowerCase();
    if (who.includes(first)) return line.slice(idx + 1).trim();
  }
  return null;
}

// POST /api/khata/calls — body { customerId? }. One batched Sarvam call writes a
// reminder line for every customer with pending udhaar; the customer side is
// simulated. This models an automated AI dunning-call run.
export async function POST(req: Request) {
  const body = await req.json().catch(() => ({}));
  const store = getStore();
  let targets = store.customers.filter((c) => c.reconPendingAmount > 0);
  if (body?.customerId) targets = targets.filter((c) => c.id === body.customerId);
  if (targets.length === 0) return Response.json({ calls: [] });

  const list = targets.map((c) => `${c.name} - Rs ${c.reconPendingAmount}`).join("\n");
  const prompt =
    "You are an automated AI calling assistant for the Kirana store " +
    `"${store.storeName}". For each customer below who owes udhaar (credit), write ONE short, ` +
    "warm, polite phone-reminder sentence in Hinglish asking them to pay. " +
    "Output exactly one line per customer in the format `Name: message`. No extra text.\n\n" +
    list;

  console.log(`[khata/calls] one batched Sarvam call for ${targets.length} customer(s)…`);
  let batched = "";
  try {
    batched = await chatComplete([{ role: "user", content: prompt }], { maxTokens: 2500, temperature: 0.5 });
  } catch (e) {
    console.log("[khata/calls] Sarvam error:", (e as Error).message);
    return Response.json({ error: "AI calling service unavailable. Please try again." }, { status: 502 });
  }
  console.log("[khata/calls] Sarvam reply:\n" + batched);

  const calls: CallResult[] = targets.map((c, i) => {
    const aiLine =
      lineFor(c.name, batched) ||
      `Namaste ${c.name.split(" ")[0]} ji, aapka udhaar Rs ${c.reconPendingAmount} pending hai, please clear kar dijiye.`;
    const sim = REPLIES[i % REPLIES.length];
    return {
      customerId: c.id,
      name: c.name,
      amount: c.reconPendingAmount,
      transcript: [
        { speaker: "AI", text: aiLine },
        { speaker: "Customer", text: sim.reply },
      ],
      outcome: sim.outcome,
      promise: sim.promise,
    };
  });

  return Response.json({ calls });
}
